name: ProductionBuildAndDeploy

on: workflow_dispatch

jobs:
  builddockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.101'

      - name: Build Asp.net core project.
        run: dotnet build TestForMultiStaging --configuration Release

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: awei0905/test:latest
  
  deploytoserver:
    needs: builddockerimage
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from dockerhub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop test
            docker rm test
            docker pull awei0905/test
            docker run --rm -p 80:5000 --name=test -it -d awei0905/test --restart=always
